version: '2.3'

services:
  telegraf:
    container_name: telegraf
    image: telegraf
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HOST_PROC=/host/proc
    privileged: true
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - ./docker/telegraf/telegraf-gpu.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/utmp:/var/run/utmp
